--SEQUENCE PER INSERIMENTO AUTOMATICO NUMERO SCHEDA
DROP SEQUENCE SEQ_N_SCHEDA;

CREATE SEQUENCE SEQ_N_SCHEDA
	START WITH 31
	INCREMENT BY 1
	NOMAXVALUE
	NOCYCLE;

--INSERIMENTO AUTOMATICO NUMERO SCHEDA
CREATE OR REPLACE TRIGGER N_SCHEDA
BEFORE INSERT ON SCHEDA_ESERCIZI
FOR EACH ROW 
WHEN (NEW.N_SCHEDA IS NULL)
--------------
DECLARE
	N_S NUMBER := SEQ_N_SCHEDA.NEXTVAL;
BEGIN 
	:NEW.N_SCHEDA := N_S;
END;
/