--SEQUENCE PER INSERIMENTO AUTOMATICO NUMERO SCHEDA
DROP SEQUENCE SEQ_N_BADGE;

CREATE SEQUENCE SEQ_N_BADGE
	START WITH 106 	
	INCREMENT BY 1
	NOMAXVALUE
	NOCYCLE;

--INSERIMENTO AUTOMATICO NUMERO BADGE
CREATE OR REPLACE TRIGGER N_BADGE
BEFORE 
INSERT ON ABBONAMENTO
FOR EACH ROW 
WHEN (NEW.BADGE IS NULL)
--------------
DECLARE
	N_S NUMBER := SEQ_N_BADGE.NEXTVAL;
BEGIN 
-- DIVIDO IL NUMERO PER 10000 E PRENDO SOLO LA PARTE DECIAMELE CONVERTITA IN CHAR PER NON PERDERE LO 0 INIZIALE!
	N_S := N_S/10000;

	:NEW.BADGE := SUBSTR(TO_CHAR(N_S,'9999.9999'),7,4);
END;
/