CREATE OR REPLACE TRIGGER ISCRITTO_MINORENNE
BEFORE INSERT ON ISCRITTO
FOR EACH ROW 
DECLARE 
	MINORENNE EXCEPTION;

BEGIN
-- GLI ISCRITTI DEVONO ESSERE TUTTI MAGGIORENNI
	IF (((SYSDATE -:NEW.DATA_NASCITA)/365) < 18) THEN RAISE MINORENNE;
END IF;

EXCEPTION 
	WHEN MINORENNE THEN 
		RAISE_APPLICATION_ERROR(-20530,'ISCRITTO MINORENNE');
END;
/