-- Assegnazione permessi

--DIRETTORE
GRANT ALL PRIVILEGES TO DIRETTORE;
GRANT EXECUTE ON LISTA_TURNI_ISTRUTTORE TO DIRETTORE;
GRANT EXECUTE ON ASSUMI_ISTRUTTORE TO DIRETTORE;
GRANT EXECUTE ON LICENZIA_ISTRUTTORE TO DIRETTORE;
GRANT EXECUTE ON CREA_EVENTO TO DIRETTORE;
GRANT EXECUTE ON INFO_ISCRITTO TO DIRETTORE;
GRANT EXECUTE ON SOTTOSCRIVI_ABBONAMENTO TO DIRETTORE;
GRANT SELECT ON LEZIONI TO DIRETTORE;
GRANT SELECT ON ABBONAMENTI_SCADUTI TO DIRETTORE;


--SEGRETARIO
GRANT INSERT, UPDATE, DELETE ON ISCRITTO TO SEGRETARIO;
GRANT INSERT, UPDATE, DELETE ON ABBONAMENTO TO SEGRETARIO;
GRANT INSERT, UPDATE, DELETE ON PARTECIPA TO SEGRETARIO;
GRANT INSERT, UPDATE, DELETE ON EVENTO TO SEGRETARIO;
GRANT EXECUTE ON INFO_ISCRITTO TO SEGRETARIO;
GRANT EXECUTE ON SOTTOSCRIVI_ABBONAMENTO TO SEGRETARIO;
GRANT EXECUTE ON ASSEGNA_CORSO TO SEGRETARIO;
GRANT SELECT ON ABBONAMENTI_SCADUTI TO SEGRETARIO;
GRANT SELECT ON CORSI_ISTRUTTORI TO SEGRETARIO;
GRANT SELECT ON EVENTI_PROGRAMMA TO SEGRETARIO;
GRANT SELECT ON ISCRITTO_EVENTO TO SEGRETARIO;

--ISTRUTTORE
GRANT INSERT, UPDATE, DELETE ON SCHEDA_ESERCIZI TO ISTRUTTORE;
GRANT INSERT, UPDATE, DELETE ON CONTIENE TO ISTRUTTORE;
GRANT INSERT, UPDATE, DELETE ON ESERCIZIO TO ISTRUTTORE;
GRANT INSERT, UPDATE, DELETE ON E_ASSEGNATA TO ISTRUTTORE;
GRANT EXECUTE ON CREA_SCHEDA TO ISTRUTTORE;
GRANT EXECUTE ON ASSEGNA_SCHEDA TO ISTRUTTORE;