CREATE OR REPLACE PROCEDURE CREA_SCHEDA
(
	CF 			SCHEDA_ESERCIZI.CF_ISTRUTTORE_SCHEDA%TYPE,
	DIFFICOLTA 		SCHEDA_ESERCIZI.LIVELLO%TYPE,
	ESERCIZIO_1 	 	CONTIENE.NOME_ESERCIZIO%TYPE,
	SERIE_1 			CONTIENE.N_SERIE%TYPE,
	RIPETIZIONI_1 		CONTIENE.N_RIPETIZIONI%TYPE,
	ESERCIZIO_2 		CONTIENE.NOME_ESERCIZIO%TYPE,
	SERIE_2 			CONTIENE.N_SERIE%TYPE,		
	RIPETIZIONI_2 		CONTIENE.N_RIPETIZIONI%TYPE,
	ESERCIZIO_3 		CONTIENE.NOME_ESERCIZIO%TYPE,
	SERIE_3 			CONTIENE.N_SERIE%TYPE,
	RIPETIZIONI_3 		CONTIENE.N_RIPETIZIONI%TYPE,
	ESERCIZIO_4 		CONTIENE.NOME_ESERCIZIO%TYPE,
	SERIE_4 			CONTIENE.N_SERIE%TYPE,
	RIPETIZIONI_4 		CONTIENE.N_RIPETIZIONI%TYPE,
	ESERCIZIO_5 		CONTIENE.NOME_ESERCIZIO%TYPE,
	SERIE_5 			CONTIENE.N_SERIE%TYPE,
	RIPETIZIONI_5 		CONTIENE.N_RIPETIZIONI%TYPE,
	ESERCIZIO_6 		CONTIENE.NOME_ESERCIZIO%TYPE,
	SERIE_6 			CONTIENE.N_SERIE%TYPE,
	RIPETIZIONI_6 		CONTIENE.N_RIPETIZIONI%TYPE
)

IS
NUMERO			   NUMBER;
FLAG 			   NUMBER;
ESERCIZIO_EXC EXCEPTION;

BEGIN

-- CONTA GLI ESERCIZI DA INSERIRE
	SELECT COUNT(*) INTO FLAG
	FROM ESERCIZIO
	WHERE NOME = ESERCIZIO_1 OR NOME = ESERCIZIO_2 OR
		  NOME = ESERCIZIO_3 OR NOME = ESERCIZIO_4 OR
		  NOME = ESERCIZIO_5 OR NOME = ESERCIZIO_6;

-- SE MINORI DI 2 LANCIA ECCEZIONE
	IF(FLAG < 2) 
	THEN RAISE ESERCIZIO_EXC;
	END IF;

-- CONTA IL NUMERO MASSIMO DI ID SCHEDA ASSEGNATO PER CALCOLARE E INSERIRE L'ID DELLA SUCCESSIVA
	SELECT MAX(N_SCHEDA) INTO NUMERO
	FROM SCHEDA_ESERCIZI;

	NUMERO := NUMERO + 1;


-- CREA LA SCHEDA
		INSERT INTO SCHEDA_ESERCIZI VALUES(CF,NUMERO,DIFFICOLTA);
-- INSERISCE I PRIMI 2 ESERCIZI
		INSERT INTO CONTIENE VALUES(NUMERO,ESERCIZIO_1,SERIE_1,RIPETIZIONI_1);
		INSERT INTO CONTIENE VALUES(NUMERO,ESERCIZIO_2,SERIE_2,RIPETIZIONI_2);
-- CONTROLLA SE C'E' UN ALTRO ESERCIZIO LO INSERISCE
	IF (ESERCIZIO_3 IS NOT NULL) THEN
		INSERT INTO CONTIENE VALUES(NUMERO,ESERCIZIO_3,SERIE_3,RIPETIZIONI_3);
	END IF;

	IF (ESERCIZIO_4 IS NOT NULL) THEN
		INSERT INTO CONTIENE VALUES(NUMERO,ESERCIZIO_4,SERIE_4,RIPETIZIONI_4);
	END IF;

	IF (ESERCIZIO_5 IS NOT NULL) THEN
		INSERT INTO CONTIENE VALUES(NUMERO,ESERCIZIO_5,SERIE_5,RIPETIZIONI_5);
	END IF;

	IF (ESERCIZIO_6 IS NOT NULL) THEN
		INSERT INTO CONTIENE VALUES(NUMERO,ESERCIZIO_6,SERIE_6,RIPETIZIONI_6);
	END IF;

EXCEPTION
	WHEN ESERCIZIO_EXC THEN
		RAISE_APPLICATION_ERROR(-20451, 'NON PUOI INSERIRE UN SOLO ESERCIZIO');


END CREA_SCHEDA;
/