CREATE OR REPLACE PROCEDURE SOTTOSCRIVI_ABBONAMENTO
(
	CF_I 			ISCRITTO.CF_ISCRITTO%TYPE,
	N_MESI 			NUMBER
)

IS 
BADGE_I 			ABBONAMENTO.BADGE%TYPE;
DURATA_NON_VALIDA 	EXCEPTION;

BEGIN

-- CONTROLLA CHE LA RICHIESTA DELL ABBONAMENTO NON SIA DIVERSA DI 1,3,6 O 12 MESI
IF(N_MESI <> 1 AND N_MESI <> 3 AND N_MESI <> 6 AND N_MESI <> 12)
	THEN RAISE DURATA_NON_VALIDA;
END IF;

-- SELEZIONA IL BADGE CHE STA USANDO L'ISCRITTO PER RINNOVARLO
-- SE L'ISCRITTO NON HA BADGE O E' LA PRIMA VOLTA CHE SOTTOSCRIVE UN ABBONAMENTO BADGE SARA' NULL
-- E SARA' GENERATO DAL TRIGGER
	SELECT MAX(BADGE) INTO BADGE_I
	FROM ISCRITTO JOIN ABBONAMENTO ON CF_ISCRITTO = CF_ISCRITTO_ABBONAMENTO
	WHERE CF_I = CF_ISCRITTO;


DELETE FROM ABBONAMENTO WHERE BADGE = BADGE_I;
INSERT INTO ABBONAMENTO VALUES (BADGE_I,CF_I,SYSDATE,SYSDATE+(30 * N_MESI));



EXCEPTION
WHEN DURATA_NON_VALIDA THEN
	RAISE_APPLICATION_ERROR(-20564,'LA DURATA DELL ABBONAMENTO PUO ESSERE DI 1,2,3,6 O 12 MESI');
WHEN NO_DATA_FOUND THEN
    BADGE_I := NULL;

END SOTTOSCRIVI_ABBONAMENTO;
/