CREATE OR REPLACE PROCEDURE LISTA_TURNI_ISTRUTTORE
(
	CF 	TURNO.CF_ISTRUTTORE_TURNO%TYPE
)
IS

CONTA_TURNI 	NUMBER;
NOT_TURNO 		EXCEPTION;
NOME_IS 		ISTRUTTORE.NOME%TYPE;
COGNOME_IS 		ISTRUTTORE.COGNOME%TYPE;
LISTA_IN 		TURNO%ROWTYPE;
CORSO_I 		CORSO%ROWTYPE;

CURSOR LISTA IS 
	SELECT CF_ISTRUTTORE_TURNO,CAP_TURNO,DATA_TURNO,ORA_TURNO,ORA_OUT_TURNO
	FROM TURNO
	WHERE CF_ISTRUTTORE_TURNO = CF;

CURSOR CORSO_ISTRUTTORE IS 
	SELECT CF_ISTRUTTORE_CORSO,CAP_CORSO,NOME_CORSO,DATA_INIZIO_CORSO,DATA_FINE_CORSO,ORA_INIZIO_CORSO
	FROM ISTRUTTORE JOIN CORSO ON CF_ISTRUTTORE = CF_ISTRUTTORE_CORSO
	WHERE CF_ISTRUTTORE = CF;


BEGIN
-- CONTA I TURNI TOTALI E PRENDE NOME E COGNOME
	SELECT COUNT(*),MAX(NOME),MAX(COGNOME) INTO CONTA_TURNI,NOME_IS,COGNOME_IS
	FROM TURNO JOIN ISTRUTTORE ON CF_ISTRUTTORE_TURNO = CF_ISTRUTTORE
	WHERE CF_ISTRUTTORE_TURNO = CF;

	IF (CONTA_TURNI < 1)
		THEN RAISE NOT_TURNO;
	END IF;
	
	DBMS_OUTPUT.PUT_LINE('ISTRUTTORE: ' || NOME_IS || ' ' || COGNOME_IS );
	DBMS_OUTPUT.PUT_LINE('TOTALE TURNI SVOLTI: ' || CONTA_TURNI);
-- CONTA I TURNI DELL'ULTIMO MESE E LI MOSTRA
	SELECT COUNT(*) INTO CONTA_TURNI
	FROM TURNO JOIN ISTRUTTORE ON CF_ISTRUTTORE_TURNO = CF_ISTRUTTORE
	WHERE CF_ISTRUTTORE_TURNO = CF AND DATA_TURNO > SYSDATE - 30;
	DBMS_OUTPUT.PUT_LINE('TOTALE TURNI ULTMIMO MESE: ' || CONTA_TURNI);

	OPEN LISTA;
	IF LISTA%NOTFOUND THEN CLOSE LISTA;
	END IF;

	LOOP
	FETCH LISTA INTO LISTA_IN;
	EXIT WHEN LISTA%NOTFOUND;
	DBMS_OUTPUT.PUT_LINE('DATA: ' || LISTA_IN.DATA_TURNO || ' ORA: ' || LISTA_IN.ORA_TURNO || ':00 - ' || LISTA_IN.ORA_OUT_TURNO || ':00 ');
	END LOOP;
	CLOSE LISTA; 
		
	-- SCORRIAMO I CORSI DELL'ISTRUTTORE
	OPEN CORSO_ISTRUTTORE;
	IF CORSO_ISTRUTTORE%NOTFOUND THEN CLOSE CORSO_ISTRUTTORE;
	END IF;

	LOOP
	FETCH CORSO_ISTRUTTORE INTO CORSO_I;
	EXIT WHEN CORSO_ISTRUTTORE%NOTFOUND;
	DBMS_OUTPUT.PUT_LINE('CORSO TENUTO: ' || CORSO_I.NOME_CORSO || ' PRESSO: ' || CORSO_I.CAP_CORSO);
	END LOOP;
	CLOSE CORSO_ISTRUTTORE;



EXCEPTION
	WHEN NOT_TURNO THEN
	RAISE_APPLICATION_ERROR(-20005,'NESSUN TURNO PER QUESTO ISTRUTTORE');

END LISTA_TURNI_ISTRUTTORE;
/