DROP TABLE STRUTTURA;
DROP TABLE ISCRITTO;
DROP TABLE CORSO;
DROP TABLE ABBONAMENTO;
DROP TABLE TURNO;
DROP TABLE EVENTO;
DROP TABLE SCHEDA_ESERCIZI;
DROP TABLE ISTRUTTORE;
DROP TABLE ESERCIZIO;
DROP TABLE GIORNI;
DROP TABLE LEZIONE;
DROP TABLE E_ASSEGNATA;
DROP TABLE PARTECIPA;
DROP TABLE CONTIENE;
DROP TABLE PREVEDE;


CREATE TABLE STRUTTURA
(   
	CAP						CHAR(5)			PRIMARY KEY,
	CAPIENZA				INT				NOT NULL,         
	TELEFONO				CHAR(10)		UNIQUE,
	VIA						VARCHAR(30)		NOT NULL,
	CITTA					VARCHAR(20)		NOT NULL
);

CREATE TABLE ISCRITTO
(
	CF_ISCRITTO				CHAR(16)	 	PRIMARY KEY,
	TELEFONO				CHAR(10)		UNIQUE,
	NOME					VARCHAR(20)		NOT NULL,
	COGNOME					VARCHAR(20)		NOT NULL,
	SESSO 					CHAR			NOT NULL,
	DATA_NASCITA			DATE			NOT NULL,
CONSTRAINT SESSO_ISCRITTO CHECK(SESSO IN ('M','F')),
CONSTRAINT CFConsentito CHECK(REGEXP_LIKE(CF_ISCRITTO, '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'))
);

CREATE TABLE ESERCIZIO
(
	NOME					VARCHAR(25)		PRIMARY KEY,
	DIFFICOLTA				VARCHAR(10)		NOT NULL,
	GRUPPO_MUSCOLARE 		VARCHAR(10)		NOT NULL,
CONSTRAINT DIFFICOLTA CHECK (DIFFICOLTA IN ('ALTA','MEDIA','BASSA')),
CONSTRAINT GRUPPO_MUSCOLARE CHECK (GRUPPO_MUSCOLARE IN ('PETTO','DORSO','BRACCIA','ADDOME','GAMBE','SPALLE'))
);

CREATE TABLE ISTRUTTORE
(
	CF_ISTRUTTORE			CHAR(16)		PRIMARY KEY,
	TELEFONO				CHAR(10)		UNIQUE,
	NOME					VARCHAR(20)		NOT NULL,
	COGNOME					VARCHAR(20)		NOT NULL,
	SESSO					CHAR 			NOT NULL,
	DATA_NASCITA			DATE 			NOT NULL,
CONSTRAINT SESSO_ISTRUTTORE CHECK(SESSO IN ('M','F')),
CONSTRAINT CFConsentito_Istruttore CHECK(REGEXP_LIKE(CF_ISTRUTTORE, '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'))
);

CREATE TABLE SCHEDA_ESERCIZI
(
	CF_ISTRUTTORE_SCHEDA	CHAR(16) 		NOT NULL,
	N_SCHEDA				INT				PRIMARY KEY,
	LIVELLO   				VARCHAR(10),
CONSTRAINT LIVELLO CHECK(LIVELLO IN ('ALTO','MEDIO','BASSO',NULL)),
FOREIGN KEY(CF_ISTRUTTORE_SCHEDA) REFERENCES ISTRUTTORE(CF_ISTRUTTORE) ON DELETE CASCADE
);

CREATE TABLE CONTIENE
(
	N_SCHEDA_FK				INT,
	NOME_ESERCIZIO			VARCHAR(25),
	N_SERIE					INT				CHECK(N_SERIE <= 5 AND N_SERIE > 0),
	N_RIPETIZIONI			INT 			CHECK(N_RIPETIZIONI <= 15 AND N_RIPETIZIONI > 0),
FOREIGN KEY(N_SCHEDA_FK) REFERENCES SCHEDA_ESERCIZI(N_SCHEDA) ON DELETE CASCADE,
FOREIGN KEY(NOME_ESERCIZIO) REFERENCES ESERCIZIO(NOME) ON DELETE CASCADE
);

CREATE TABLE E_ASSEGNATA
(
	CF_ISCRITTO_FK			CHAR(16),
	N_SCHEDA_FK				INT,
	DATA_INIZIO				DATE			NOT NULL,
	DATA_FINE				DATE			NOT NULL,
PRIMARY KEY(CF_ISCRITTO_FK,N_SCHEDA_FK),
FOREIGN KEY(CF_ISCRITTO_FK) REFERENCES ISCRITTO(CF_ISCRITTO) ON DELETE CASCADE,
FOREIGN KEY(N_SCHEDA_FK) REFERENCES SCHEDA_ESERCIZI(N_SCHEDA) ON DELETE CASCADE
);

CREATE TABLE TURNO
(
	CF_ISTRUTTORE_TURNO		CHAR(16) 		NOT NULL,
	CAP_TURNO				CHAR(5),
	DATA_TURNO				DATE,			
	ORA_TURNO				CHAR(2),		
	ORA_OUT_TURNO			CHAR(2) 		NOT NULL,
PRIMARY KEY(DATA_TURNO,ORA_TURNO,CAP_TURNO),
FOREIGN KEY(CF_ISTRUTTORE_TURNO) REFERENCES ISTRUTTORE(CF_ISTRUTTORE) ON DELETE CASCADE,
FOREIGN KEY(CAP_TURNO) REFERENCES STRUTTURA(CAP) ON DELETE CASCADE
);	

CREATE TABLE EVENTO
(
	NOME_EVENTO				VARCHAR(25)		PRIMARY KEY,
	CAP_EVENTO				CHAR(5) 		NOT NULL,
	DATA					DATE			NOT NULL,
FOREIGN KEY(CAP_EVENTO) REFERENCES STRUTTURA(CAP) ON DELETE CASCADE
);

CREATE TABLE PARTECIPA
(
	CF_ISCRITTO_PARTECIPA	CHAR(16),
	NOME_PARTECIPA			VARCHAR(25),
PRIMARY KEY(CF_ISCRITTO_PARTECIPA,NOME_PARTECIPA),
FOREIGN KEY(CF_ISCRITTO_PARTECIPA) REFERENCES ISCRITTO(CF_ISCRITTO) ON DELETE CASCADE ,
FOREIGN KEY(NOME_PARTECIPA) REFERENCES EVENTO(NOME_EVENTO) ON DELETE CASCADE
);

CREATE TABLE ABBONAMENTO
(
	BADGE					CHAR(4)			PRIMARY KEY,
	CF_ISCRITTO_ABBONAMENTO	CHAR(16) 		NOT NULL,
	DATA_INIZIO				DATE			NOT NULL,
	DATA_SCADENZA			DATE			NOT NULL,
FOREIGN KEY(CF_ISCRITTO_ABBONAMENTO) REFERENCES ISCRITTO(CF_ISCRITTO) ON DELETE CASCADE
);

CREATE TABLE CORSO
(
	CF_ISTRUTTORE_CORSO		CHAR(16) 		NOT NULL,
	CAP_CORSO				CHAR(5) ,
	NOME_CORSO				VARCHAR(20),
	DATA_INIZIO_CORSO		DATE			NOT NULL,
	DATA_FINE_CORSO			DATE			NOT NULL,
	ORA_INIZIO_CORSO		CHAR(2)			NOT NULL,
PRIMARY KEY(NOME_CORSO,CAP_CORSO),
FOREIGN KEY(CF_ISTRUTTORE_CORSO) REFERENCES ISTRUTTORE(CF_ISTRUTTORE) ON DELETE SET NULL,
FOREIGN KEY(CAP_CORSO) REFERENCES STRUTTURA(CAP) ON DELETE CASCADE
);

CREATE TABLE PREVEDE
(
	BADGE_FK				CHAR(4),
	CAP_CORSO_FK			CHAR(5),
	NOME_CORSO_FK			VARCHAR(20),
PRIMARY KEY(BADGE_FK,NOME_CORSO_FK,CAP_CORSO_FK),
FOREIGN KEY(BADGE_FK) REFERENCES ABBONAMENTO(BADGE) ON DELETE CASCADE,
FOREIGN KEY(NOME_CORSO_FK,CAP_CORSO_FK) REFERENCES CORSO(NOME_CORSO,CAP_CORSO) ON DELETE CASCADE
);

CREATE TABLE LEZIONE
(
	CAP_LEZIONE				CHAR(5) 		NOT NULL,
	NOME_LEZIONE			VARCHAR(20) 	NOT NULL,
	DATA_LEZIONE			DATE			NOT NULL,
	ORA_INIZIO_LEZIONE		CHAR(2)			NOT NULL,
	ORA_FINE_LEZIONE 		CHAR(2)			NOT NULL,
	N_STANZA				INT 			NOT NULL,
PRIMARY KEY(DATA_LEZIONE,ORA_INIZIO_LEZIONE,ORA_FINE_LEZIONE,NOME_LEZIONE,CAP_LEZIONE),
FOREIGN KEY(NOME_LEZIONE,CAP_LEZIONE) REFERENCES CORSO(NOME_CORSO,CAP_CORSO) ON DELETE CASCADE 
);

CREATE TABLE GIORNI
(
	GIORNO_CORSO			VARCHAR(10),
	CAP_STRUTTURA_FK		CHAR(5),
	NOME_CORSO_GIORNO		VARCHAR(20),
PRIMARY KEY(GIORNO_CORSO,NOME_CORSO_GIORNO,CAP_STRUTTURA_FK),
FOREIGN KEY(NOME_CORSO_GIORNO,CAP_STRUTTURA_FK) REFERENCES CORSO(NOME_CORSO,CAP_CORSO) ON DELETE CASCADE
);