---VISTA DIRETTORE PER CATALOGO CORSI
CREATE VIEW CORSI_ISTRUTTORI AS  
    SELECT NOME_CORSO  AS CORSO,CAP_CORSO AS CAP,CITTA,COGNOME AS ISTRUTTORE,DATA_INIZIO_CORSO AS INIZIO,ORA_INIZIO_CORSO AS ORARIO,DATA_FINE_CORSO AS FINE  
    FROM ISTRUTTORE JOIN CORSO ON CF_ISTRUTTORE_CORSO = CF_ISTRUTTORE  
        JOIN STRUTTURA ON CAP_CORSO = CAP;
