--VISUALIZZA GLI ISCRITTI A CUI E' SCADUTO L'ABBONAMENTO
CREATE VIEW ABBONAMENTI_SCADUTI AS
SELECT CF_ISCRITTO,COGNOME,BADGE
FROM PREVEDE JOIN ABBONAMENTO ON BADGE_FK = BADGE 
	JOIN ISCRITTO ON CF_ISCRITTO_ABBONAMENTO = CF_ISCRITTO
WHERE DATA_SCADENZA < SYSDATE;
