--VISUALIZZA TUTTE LE LEZIONI SVOLTESI NELL'ULTIMO MESE
CREATE VIEW LEZIONI AS
SELECT NOME_LEZIONE AS CORSO, CAP_LEZIONE AS CAP,DATA_LEZIONE AS DATA,
	ORA_INIZIO_LEZIONE AS ORA, ORA_FINE_LEZIONE AS ORA_FINE,N_STANZA AS STANZA 
FROM LEZIONE
WHERE DATA_LEZIONE > SYSDATE - 30
ORDER BY DATA,CAP DESC;

--VISUALIZZA GLI ISCRITTI A CUI E' SCADUTO L'ABBONAMENTO
CREATE VIEW ABBONAMENTI_SCADUTI AS
SELECT CF_ISCRITTO,COGNOME,BADGE
FROM PREVEDE JOIN ABBONAMENTO ON BADGE_FK = BADGE 
	JOIN ISCRITTO ON CF_ISCRITTO_ABBONAMENTO = CF_ISCRITTO
WHERE DATA_SCADENZA < SYSDATE;

---VISTA DIRETTORE PER CATALOGO CORSI
CREATE VIEW CORSI_ISTRUTTORI AS  
    SELECT NOME_CORSO  AS CORSO,CAP_CORSO AS CAP,CITTA,COGNOME AS ISTRUTTORE,DATA_INIZIO_CORSO AS INIZIO,ORA_INIZIO_CORSO AS ORARIO,DATA_FINE_CORSO AS FINE  
    FROM ISTRUTTORE JOIN CORSO ON CF_ISTRUTTORE_CORSO = CF_ISTRUTTORE  
        JOIN STRUTTURA ON CAP_CORSO = CAP;


CREATE VIEW EVENTI_PROGRAMMA AS
SELECT E.NOME_EVENTO,S.CITTA,S.CAP,S.VIA,E.DATA 
FROM EVENTO E JOIN STRUTTURA S ON E.CAP_EVENTO = S.CAP
WHERE DATA > SYSDATE;

CREATE VIEW ISCRITTO_EVENTO AS
SELECT NOME, COGNOME, NOME_EVENTO, DATA 
FROM ISCRITTO JOIN PARTECIPA ON CF_ISCRITTO_PARTECIPA = CF_ISCRITTO 
	JOIN EVENTO ON NOME_PARTECIPA = NOME_EVENTO;